#!/bin/sh

### BEGIN INIT INFO
# Provides:          web-lights
# Required-Start:    $remote_fs $syslog $network olad
# Required-Stop:     $remote_fs $syslog $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: WebLights Server
# Description:       A web client for OLA for controlling RGB LEDs
### END INIT INFO

PATH=/usr/local/bin:/bin:/usr/bin
NAME=web-lights
DAEMON=/usr/bin/$NAME
PYDAEMON="/usr/bin/python $DAEMON"
PIDFILE=/var/run/$NAME.pid
DESC="WebLights Server"
USER=pi


[ -x "$DAEMON" ] || exit 0

. /lib/lsb/init-functions

case "$1" in
  start)
    # master switch
	log_daemon_msg "Starting $DESC" "$NAME"
	/sbin/start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --umask 0002 --chuid $USER --exec $PYDAEMON 
	log_end_msg $?
    ;;
  stop)
    # master switch
    log_daemon_msg "Stopping $DESC" "$NAME"
    /sbin/start-stop-daemon --stop --pidfile $PIDFILE --chuid $USER --exec $PYDAEMON --retry 10
    /bin/rm -f $PIDFILE
    log_end_msg $?
    ;;
  reload|restart)
    $0 stop && $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $PYDAEMON $NAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
